// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/leader_board.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Api {
  public static partial class LeaderBoard
  {
    static readonly string __ServiceName = "api.LeaderBoard";

    static readonly grpc::Marshaller<global::Api.PlayerScore> __Marshaller_api_PlayerScore = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Api.PlayerScore.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Api.PlayerRank> __Marshaller_api_PlayerRank = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Api.PlayerRank.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Api.PlayerId> __Marshaller_api_PlayerId = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Api.PlayerId.Parser.ParseFrom);

    static readonly grpc::Method<global::Api.PlayerScore, global::Api.PlayerRank> __Method_AddScore = new grpc::Method<global::Api.PlayerScore, global::Api.PlayerRank>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AddScore",
        __Marshaller_api_PlayerScore,
        __Marshaller_api_PlayerRank);

    static readonly grpc::Method<global::Api.PlayerId, global::Api.PlayerRank> __Method_GetRank = new grpc::Method<global::Api.PlayerId, global::Api.PlayerRank>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetRank",
        __Marshaller_api_PlayerId,
        __Marshaller_api_PlayerRank);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Api.LeaderBoardReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of LeaderBoard</summary>
    [grpc::BindServiceMethod(typeof(LeaderBoard), "BindService")]
    public abstract partial class LeaderBoardBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Api.PlayerRank> AddScore(global::Api.PlayerScore request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Api.PlayerRank> GetRank(global::Api.PlayerId request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for LeaderBoard</summary>
    public partial class LeaderBoardClient : grpc::ClientBase<LeaderBoardClient>
    {
      /// <summary>Creates a new client for LeaderBoard</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public LeaderBoardClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for LeaderBoard that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public LeaderBoardClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected LeaderBoardClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected LeaderBoardClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Api.PlayerRank AddScore(global::Api.PlayerScore request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddScore(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Api.PlayerRank AddScore(global::Api.PlayerScore request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AddScore, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Api.PlayerRank> AddScoreAsync(global::Api.PlayerScore request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddScoreAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Api.PlayerRank> AddScoreAsync(global::Api.PlayerScore request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AddScore, null, options, request);
      }
      public virtual global::Api.PlayerRank GetRank(global::Api.PlayerId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetRank(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Api.PlayerRank GetRank(global::Api.PlayerId request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetRank, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Api.PlayerRank> GetRankAsync(global::Api.PlayerId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetRankAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Api.PlayerRank> GetRankAsync(global::Api.PlayerId request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetRank, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override LeaderBoardClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new LeaderBoardClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(LeaderBoardBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_AddScore, serviceImpl.AddScore)
          .AddMethod(__Method_GetRank, serviceImpl.GetRank).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, LeaderBoardBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_AddScore, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Api.PlayerScore, global::Api.PlayerRank>(serviceImpl.AddScore));
      serviceBinder.AddMethod(__Method_GetRank, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Api.PlayerId, global::Api.PlayerRank>(serviceImpl.GetRank));
    }

  }
}
#endregion
